import Footer from "@/components/footer/Footer";
import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Header from "@/components/header/Header";
import GlobalStyling from "./GlobalStyling";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='ko'>
            <body className={inter.className}>
                <main className='container'>
                    <Header />
                    {children}
                    <Footer />
                </main>
            </body>
        </html>
    );
}
